# Generated by Django 5.2.1 on 2025-06-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='profileimages/')),
                ('points', models.IntegerField(default=0)),
                ('achivements', models.IntegerField(default=0)),
                ('certificate', models.IntegerField(default=0)),
            ],
        ),
    ]
