# Generated by Django 5.2.1 on 2025-06-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('thump', models.ImageField(upload_to='thumpnails/')),
                ('users', models.ManyToManyField(null=True, related_name='reg_courses', to='users.users')),
            ],
        ),
    ]
